const demoEmails=[
{id:"demo_01",sender:"security@paypa1-login.com",recipient:"analyst@phishguard.demo",subject:"Your account will be suspended!",body:"URGENT: Verify your account immediately. Sign in now to avoid suspension.",urls:["http://paypa1-login.com/verify"],attachments:[],headers:{}},
{id:"demo_02",sender:"billing@micros0ft-support.com",recipient:"analyst@phishguard.demo",subject:"Microsoft 365 payment failed",body:"Your subscription will be terminated today. Login immediately and update your payment information.",urls:["http://micros0ft-support.com/login"],attachments:[],headers:{}},
{id:"demo_03",sender:"alerts@amaz0n-orders.com",recipient:"analyst@phishguard.demo",subject:"Unusual Amazon order detected",body:"We detected an unusual purchase. Verify your account now to cancel the order.",urls:["http://amaz0n-orders.com/verify"],attachments:[],headers:{}},
{id:"demo_04",sender:"support@netfIix-billing.com",recipient:"analyst@phishguard.demo",subject:"Netflix account on hold",body:"Payment declined. Confirm your billing details immediately to restore access.",urls:["http://netfiix-billing.com/update"],attachments:[],headers:{}},
{id:"demo_05",sender:"security@googIe-alerts.com",recipient:"analyst@phishguard.demo",subject:"Critical security alert",body:"Suspicious login detected. Verify your password immediately.",urls:["http://googie-alerts.com/security"],attachments:[],headers:{}},
{id:"demo_06",sender:"admin@company-payroll-update.com",recipient:"analyst@phishguard.demo",subject:"Urgent payroll verification required",body:"Payroll processing is blocked. Confirm your employee credentials immediately.",urls:["http://company-payroll-update.com/auth"],attachments:[],headers:{}},
{id:"demo_07",sender:"delivery@dhl-track-package.com",recipient:"analyst@phishguard.demo",subject:"Package delivery failed",body:"Your parcel cannot be delivered. Pay the redelivery fee today.",urls:["http://dhl-track-package.com/payment"],attachments:[],headers:{}},
{id:"demo_08",sender:"hr@company-careers.example",recipient:"analyst@phishguard.demo",subject:"Action required: employee profile review",body:"Please review your employee profile before the deadline.",urls:["https://company-careers.example/profile"],attachments:[],headers:{}},
{id:"demo_09",sender:"notifications@shared-docs.example",recipient:"analyst@phishguard.demo",subject:"A document was shared with you",body:"A document has been shared. Review the link when available.",urls:["https://shared-docs.example/view"],attachments:[],headers:{}},
{id:"demo_10",sender:"events@conference.example",recipient:"analyst@phishguard.demo",subject:"Conference registration reminder",body:"Registration closes soon. Review your registration details.",urls:["https://conference.example/register"],attachments:[],headers:{}},
{id:"demo_11",sender:"support@cloud-storage.example",recipient:"analyst@phishguard.demo",subject:"Storage quota nearly full",body:"Your storage is nearly full. Review storage settings to avoid interruption.",urls:["https://cloud-storage.example/settings"],attachments:[],headers:{}},
{id:"demo_12",sender:"finance@vendor.example",recipient:"analyst@phishguard.demo",subject:"Invoice review requested",body:"Please review the attached invoice information and confirm when convenient.",urls:[],attachments:["invoice.pdf"],headers:{}},
{id:"demo_13",sender:"updates@github.com",recipient:"analyst@phishguard.demo",subject:"Repository activity summary",body:"Here is your weekly repository activity summary.",urls:["https://github.com/"],attachments:[],headers:{}},
{id:"demo_14",sender:"no-reply@classroom.google.com",recipient:"analyst@phishguard.demo",subject:"New assignment posted",body:"A new assignment has been posted in your class.",urls:["https://classroom.google.com/"],attachments:[],headers:{}},
{id:"demo_15",sender:"messages-noreply@linkedin.com",recipient:"analyst@phishguard.demo",subject:"You have a new LinkedIn message",body:"You received a new professional networking message.",urls:["https://www.linkedin.com/"],attachments:[],headers:{}},
{id:"demo_16",sender:"team@notion.so",recipient:"analyst@phishguard.demo",subject:"Workspace weekly digest",body:"Your weekly workspace activity digest is ready.",urls:["https://www.notion.so/"],attachments:[],headers:{}},
{id:"demo_17",sender:"notifications@figma.com",recipient:"analyst@phishguard.demo",subject:"New comment on your design",body:"A teammate commented on your design file.",urls:["https://www.figma.com/"],attachments:[],headers:{}},
{id:"demo_18",sender:"calendar-notification@google.com",recipient:"analyst@phishguard.demo",subject:"Meeting reminder",body:"Reminder for your scheduled team meeting today.",urls:["https://calendar.google.com/"],attachments:[],headers:{}},
{id:"demo_19",sender:"noreply@github.com",recipient:"analyst@phishguard.demo",subject:"Pull request review requested",body:"A collaborator requested your review on a pull request.",urls:["https://github.com/"],attachments:[],headers:{}},
{id:"demo_20",sender:"newsletter@python.org",recipient:"analyst@phishguard.demo",subject:"Python community newsletter",body:"News and updates from the Python community.",urls:["https://www.python.org/"],attachments:[],headers:{}}
];
let demoMode=false;
function renderInboxRows(rows,label){const p=document.getElementById("investigation");p.innerHTML='<h3>Gmail Investigations</h3><div class="panel-sub">'+label+'</div><div id="gmailStatus" class="scan-result">'+rows.length+' emails analyzed automatically</div><div id="gmailList"></div>';const list=document.getElementById("gmailList");list.innerHTML=rows.map(row=>{const e=row.email||{},r=row.analysis||{},reasons=(r.reasons||[]).slice(0,2).map(esc).join(" • ");return '<div class="threat" style="display:grid;grid-template-columns:minmax(0,1fr) auto auto auto;gap:10px;align-items:center"><div style="min-width:0"><b style="display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis">'+esc(e.subject||"No subject")+'</b><small style="display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis">'+esc(e.sender||"")+(reasons?' • '+reasons:'')+'</small></div><span style="'+inboxVerdictStyle(r.verdict)+';padding:6px 10px;border-radius:999px;font-size:12px;font-weight:800;white-space:nowrap">'+esc(inboxRiskLabel(r.verdict))+' · '+esc(r.risk_score??0)+'%</span><button onclick="report(\''+esc(r.email_id||e.id)+'\')">REPORT</button><button onclick="quarantine(\''+esc(r.email_id||e.id)+'\')">QUARANTINE</button></div>'}).join("");requestAnimationFrame(bind3DTilt)}
async function loadDemoEmails(){const p=document.getElementById("investigation");p.innerHTML='<h3>Demo Inbox Investigations</h3><div class="panel-sub">20 safe and phishing simulation emails are being analyzed by the live detection engine.</div><div id="gmailStatus" class="scan-result">⏳ Auto-analyzing 20 demo emails...</div><div id="gmailList"></div>';const rows=[];for(let n=0;n<demoEmails.length;n++){document.getElementById("gmailStatus").textContent='⏳ Analyzing demo email '+(n+1)+' of '+demoEmails.length+'...';try{const r=await api("/analyze",{method:"POST",body:JSON.stringify(demoEmails[n])});rows.push({email:demoEmails[n],analysis:r})}catch(e){rows.push({email:demoEmails[n],analysis:{email_id:demoEmails[n].id,verdict:"SUSPICIOUS",risk_score:50,reasons:["Demo analysis unavailable - manual review required"]}})}}renderInboxRows(rows,"DEMO MODE · 20 simulated emails analyzed automatically. Use Report or Quarantine to demonstrate the response workflow.");showToast("20 demo emails analyzed")}
