function checkEmail(){const email=document.getElementById("email").value;const message=document.getElementById("emailMessage");if(email===""){message.textContent="";return}if(email.includes("@")){message.textContent="✓ Looks good!";message.style.color="#FF9A8B"}else{message.textContent="Please enter a valid email.";message.style.color="#FF6F61"}}
function checkPassword(){const password=document.getElementById("password").value;const strength=document.getElementById("strength");if(password.length>=8){strength.textContent="Strong";strength.style.color="#FF9A8B"}else if(password.length>=5){strength.textContent="Medium";strength.style.color="#FFD0A6"}else{strength.textContent="Weak";strength.style.color="#FF6F61"}}
function togglePassword(){const password=document.getElementById("password");password.type=password.type==="password"?"text":"password"}
function useDemo(){document.getElementById("email").value="analyst@phishguard.demo";document.getElementById("password").value="Demo@1234";checkEmail();checkPassword();document.getElementById("loginMessage").textContent="✓ Demo account loaded — click Sign In"}
function login(){const email=document.getElementById("email").value;const password=document.getElementById("password").value;const button=document.getElementById("signinButton");const message=document.getElementById("loginMessage");if(email==="analyst@phishguard.demo"&&password==="Demo@1234"){button.textContent="⏳ Authenticating...";message.textContent="✓ Authentication successful";setTimeout(function(){document.getElementById("loginPage").style.opacity="0";document.getElementById("loginPage").style.transform="scale(0.95)";setTimeout(function(){document.getElementById("loginPage").style.display="none";document.getElementById("dashboard").classList.add("show");window.scrollTo(0,0)},500)},800)}else{message.textContent="⚠️ Invalid login. Click 'Use Demo Account'.";message.style.color="#FF6F61"}}
function googleLogin(){alert("Google login is a front-end demo.")}
function logout(){document.getElementById("dashboard").classList.remove("show");document.getElementById("loginPage").style.display="grid";document.getElementById("loginPage").style.opacity="1";document.getElementById("loginPage").style.transform="scale(1)";document.getElementById("password").value="";document.getElementById("loginMessage").textContent="";document.getElementById("signinButton").textContent="🛡️ Sign In";window.scrollTo(0,0)}
function scanURL(){const url=document.getElementById("urlInput").value;const result=document.getElementById("scanResult");if(url.trim()===""){result.textContent="⚠️ Enter a URL first.";result.style.color="#FF6F61";return}result.style.color="#FF9A8B";result.textContent="⏳ AI analyzing URL behavior...";setTimeout(function(){result.textContent="⚠️ Demo result: suspicious indicators detected — investigation recommended."},1000)}
function scrollToSection(id){document.getElementById(id).scrollIntoView({behavior:"smooth"})}
document.addEventListener("click",function(e){const ripple=document.createElement("span");ripple.className="ripple";ripple.style.left=e.clientX+"px";ripple.style.top=e.clientY+"px";document.body.appendChild(ripple);setTimeout(()=>ripple.remove(),700);const interactive=e.target.closest("button,.feature,.dashboard-card,.threat,.stat,.forgot,.google");if(interactive&&!interactive.classList.contains("ripple")){interactive.animate([{transform:"scale(1)"},{transform:"scale(.97)"},{transform:"scale(1)"}],{duration:180,easing:"ease-out"})}});
function showToast(text){const old=document.querySelector(".toast");if(old)old.remove();const t=document.createElement("div");t.className="toast";t.textContent=text;document.body.appendChild(t);setTimeout(()=>t.remove(),2600)}
const originalGoogleLogin=googleLogin;googleLogin=function(){showToast("Google authentication demo selected");originalGoogleLogin()};
document.querySelectorAll(".threat").forEach(item=>{item.addEventListener("click",()=>{const title=item.querySelector("b")?.textContent||"Threat";showToast("Investigation opened: "+title)})});
const originalScanURL=scanURL;scanURL=function(){const input=document.getElementById("urlInput");if(!input.value.trim()){originalScanURL();return}const result=document.getElementById("scanResult");result.textContent="◌ Running URL X-Ray • checking domain • redirects • reputation...";result.style.color="#FFB39F";setTimeout(()=>{originalScanURL()},700)};
document.querySelector(".forgot")?.addEventListener("click",()=>{showToast("Password reset flow opened — demo mode")});
document.querySelector(".login-card .green:last-child")?.addEventListener("click",()=>{showToast("Account creation flow — demo mode")});