const API_BASE="https://phishguard-api-wrjw.onrender.com";
let googleSession=localStorage.getItem("phishguard_google_session")||"";
async function api(path,options={}){const headers={"Content-Type":"application/json",...(options.headers||{})};if(googleSession)headers["X-Session-ID"]=googleSession;const r=await fetch(API_BASE+path,{...options,headers});if(!r.ok){let d={};try{d=await r.json()}catch(e){}throw new Error(d.detail||"Request failed")}return r.json()}
function openDashboard(){document.getElementById("loginPage").style.display="none";document.getElementById("dashboard").classList.add("show");loadEmails();loadCampaigns()}
function handleOAuthReturn(){const h=new URLSearchParams(location.hash.slice(1));const s=h.get("google_session"),err=h.get("google_error");if(s){googleSession=s;localStorage.setItem("phishguard_google_session",s);history.replaceState(null,"",location.pathname);openDashboard();showToast("Google Gmail connected") }else if(err){history.replaceState(null,"",location.pathname);document.getElementById("loginMessage").textContent="⚠️ Google login failed: "+err}}
function checkEmail(){const e=document.getElementById("email").value,m=document.getElementById("emailMessage");m.textContent=e?(e.includes("@")?"✓ Looks good!":"Please enter a valid email."):""}
function checkPassword(){const p=document.getElementById("password").value,s=document.getElementById("strength");s.textContent=p.length>=8?"Strong":p.length>=5?"Medium":"Weak"}
function togglePassword(){const p=document.getElementById("password");p.type=p.type==="password"?"text":"password"}
function useDemo(){googleSession="";localStorage.removeItem("phishguard_google_session");document.getElementById("email").value="analyst@phishguard.demo";document.getElementById("password").value="Demo@1234";checkEmail();checkPassword();document.getElementById("loginMessage").textContent="✓ Demo account loaded — click Sign In"}
function login(){const e=document.getElementById("email").value,p=document.getElementById("password").value,m=document.getElementById("loginMessage");if(e==="analyst@phishguard.demo"&&p==="Demo@1234"){googleSession="";localStorage.removeItem("phishguard_google_session");m.textContent="✓ Authentication successful";setTimeout(openDashboard,300)}else m.textContent="⚠️ Invalid login. Use Google or click 'Use Demo Account'."}
function googleLogin(){window.location.href=API_BASE+"/auth/google"}
async function logout(){try{if(googleSession)await api("/auth/logout",{method:"POST"})}catch(e){}googleSession="";localStorage.removeItem("phishguard_google_session");document.getElementById("dashboard").classList.remove("show");document.getElementById("loginPage").style.display="grid"}
function scrollToSection(id){document.getElementById(id)?.scrollIntoView({behavior:"smooth"})}
function showToast(t){let x=document.querySelector(".toast");if(x)x.remove();x=document.createElement("div");x.className="toast";x.textContent=t;document.body.appendChild(x);setTimeout(()=>x.remove(),2600)}
async function scanURL(){const u=document.getElementById("urlInput").value.trim(),r=document.getElementById("scanResult");if(!u){r.textContent="⚠️ Enter a URL first.";return}r.innerHTML="⏳ Scanning URL with live detection engine...";try{const x=await api("/scan-url?url="+encodeURIComponent(u));const reasons=(x.reasons||[]).map(esc).join(" • ");r.innerHTML='<div><b>'+esc(x.verdict)+' — '+esc(x.risk_score)+'% RISK</b><br><span>'+reasons+'</span></div>';showToast("URL scan complete")}catch(e){r.textContent="⚠️ URL scan failed: "+e.message}}
function esc(v){const d=document.createElement("div");d.textContent=v??"";return d.innerHTML}
async function loadEmails(){const p=document.getElementById("investigation");p.innerHTML='<h3>Gmail Investigations</h3><div class="panel-sub">Live recent Gmail messages</div><div id="gmailStatus" class="scan-result">⏳ Loading...</div><div id="gmailList"></div><div id="analysisOutput"></div>';try{const emails=await api("/emails"),list=document.getElementById("gmailList");document.getElementById("gmailStatus").textContent=emails.length+" emails loaded";list.innerHTML=emails.map(e=>'<div class="threat"><div><b>'+esc(e.subject||"No subject")+'</b><small>'+esc(e.sender)+'</small></div><button onclick="analyzeGmail(\''+e.id+'\')">ANALYZE</button></div>').join("")}catch(e){document.getElementById("gmailStatus").textContent="⚠️ Backend/Gmail connection failed: "+e.message}}
async function analyzeGmail(id){const o=document.getElementById("analysisOutput");o.innerHTML='<div class="scan-result">⏳ Analyzing...</div>';try{const r=await api("/analyze-gmail/"+encodeURIComponent(id),{method:"POST"});o.innerHTML='<div class="panel" style="margin-top:12px"><h3>'+esc(r.verdict)+' — '+esc(r.risk_score)+'% RISK</h3><div class="panel-sub">'+(r.reasons||[]).map(esc).join(" • ")+'</div><div class="scan-row"><button onclick="report(\''+r.email_id+'\')">REPORT</button><button onclick="quarantine(\''+r.email_id+'\')">QUARANTINE</button></div><div id="reportOutput"></div></div>';showToast("Analysis complete")}catch(e){o.textContent="Analysis failed: "+e.message}}
async function report(id){const o=document.getElementById("reportOutput");try{const r=await api("/report/"+encodeURIComponent(id)),i=r.indicators_of_compromise||{};o.innerHTML='<div class="demo"><h4>Incident Report</h4><p>Verdict: '+esc(r.verdict)+' | Risk: '+esc(r.risk_score)+'%</p><p>Sender: '+esc(i.sender)+'</p><p>Action: '+esc(r.recommended_action)+'</p></div>'}catch(e){showToast("Report failed: "+e.message)}}
async function quarantine(id){try{const r=await api("/quarantine/"+encodeURIComponent(id),{method:"POST"});showToast("Email "+r.status)}catch(e){showToast("Quarantine failed: "+e.message)}}
async function loadCampaigns(){const o=document.getElementById("campaignOutput");o.innerHTML='<div class="scan-result">⏳ Loading campaign intelligence...</div>';try{const rows=await api("/campaigns");o.innerHTML=rows.length?rows.map(c=>'<div class="threat"><div><b>'+esc(c.campaign_id||"Detected Campaign")+'</b><small>'+esc(c.reason||c.description||"Related phishing emails detected")+'</small></div><span class="badge">CAMPAIGN</span></div>').join(""):'<div class="scan-result">No active campaign detected.</div>';document.getElementById("campaignPanel")?.scrollIntoView({behavior:"smooth"})}catch(e){o.textContent="Campaign load failed: "+e.message}}
window.addEventListener("DOMContentLoaded",handleOAuthReturn);
