const API_BASE="https://phishguard-api-wrjw.onrender.com";
let googleSession=localStorage.getItem("phishguard_google_session")||"";
async function api(path,options={}){const headers={"Content-Type":"application/json",...(options.headers||{})};if(googleSession)headers["X-Session-ID"]=googleSession;const r=await fetch(API_BASE+path,{...options,headers});if(!r.ok){let d={};try{d=await r.json()}catch(e){}throw new Error(d.detail||"Request failed")}return r.json()}
function openDashboard(){document.getElementById("loginPage").style.display="none";document.getElementById("dashboard").classList.add("show");loadEmails();loadCampaigns()}
function handleOAuthReturn(){const h=new URLSearchParams(location.hash.slice(1));const s=h.get("google_session"),err=h.get("google_error");if(s){googleSession=s;localStorage.setItem("phishguard_google_session",s);history.replaceState(null,"",location.pathname);openDashboard();showToast("Google Gmail connected") }else if(err){history.replaceState(null,"",location.pathname);document.getElementById("loginMessage").textContent="⚠️ Google login failed: "+err}}
function checkEmail(){const e=document.getElementById("email").value,m=document.getElementById("emailMessage");m.textContent=e?(e.includes("@")?"✓ Looks good!":"Please enter a valid email."):""}
function checkPassword(){const p=document.getElementById("password").value,s=document.getElementById("strength");s.textContent=p.length>=8?"Strong":p.length>=5?"Medium":"Weak"}
function togglePassword(){const p=document.getElementById("password");p.type=p.type==="password"?"text":"password"}
function useDemo(){googleSession="";localStorage.removeItem("phishguard_google_session");document.getElementById("email").value="analyst@phishguard.demo";document.getElementById("password").value="Demo@1234";checkEmail();checkPassword();document.getElementById("loginMessage").textContent="✓ Demo account loaded — click Sign In"}
function login(){const e=document.getElementById("email").value,p=document.getElementById("password").value,m=document.getElementById("loginMessage");if(e==="analyst@phishguard.demo"&&p==="Demo@1234"){googleSession="";localStorage.removeItem("phishguard_google_session");m.textContent="✓ Authentication successful";setTimeout(openDashboard,300)}else m.textContent="⚠️ Invalid login. Use Google or click 'Use Demo Account'."}
function googleLogin(){window.location.href=API_BASE+"/auth/google"}
async function logout(){try{if(googleSession)await api("/auth/logout",{method:"POST"})}catch(e){}googleSession="";localStorage.removeItem("phishguard_google_session");document.getElementById("dashboard").classList.remove("show");document.getElementById("loginPage").style.display="grid"}
function scrollToSection(id){document.getElementById(id)?.scrollIntoView({behavior:"smooth"})}
function showToast(t){let x=document.querySelector(".toast");if(x)x.remove();x=document.createElement("div");x.className="toast";x.textContent=t;document.body.appendChild(x);setTimeout(()=>x.remove(),2600)}
async function scanURL(){const u=document.getElementById("urlInput").value.trim(),r=document.getElementById("scanResult");if(!u){r.textContent="⚠️ Enter a URL first.";return}r.innerHTML="⏳ Scanning URL with live detection engine...";try{const x=await api("/scan-url?url="+encodeURIComponent(u));const reasons=(x.reasons||[]).map(esc).join(" • ");r.innerHTML='<div><b>'+esc(x.verdict)+' — '+esc(x.risk_score)+'% RISK</b><br><span>'+reasons+'</span></div>';showToast("URL scan complete")}catch(e){r.textContent="⚠️ URL scan failed: "+e.message}}
function esc(v){const d=document.createElement("div");d.textContent=v??"";return d.innerHTML}
async function loadEmails(){const p=document.getElementById("investigation");p.innerHTML='<h3>Gmail Investigations</h3><div class="panel-sub">Live recent Gmail messages</div><div id="gmailStatus" class="scan-result">⏳ Loading...</div><div id="gmailList"></div><div id="analysisOutput"></div>';try{const emails=await api("/emails"),list=document.getElementById("gmailList");document.getElementById("gmailStatus").textContent=emails.length+" emails loaded";list.innerHTML=emails.map(e=>'<div class="threat"><div><b>'+esc(e.subject||"No subject")+'</b><small>'+esc(e.sender)+'</small></div><button onclick="analyzeGmail(\''+e.id+'\')">ANALYZE</button></div>').join("");requestAnimationFrame(bind3DTilt)}catch(e){document.getElementById("gmailStatus").textContent="⚠️ Backend/Gmail connection failed: "+e.message}}
async function analyzeGmail(id){const o=document.getElementById("analysisOutput");o.innerHTML='<div class="scan-result">⏳ Analyzing...</div>';try{const r=await api("/analyze-gmail/"+encodeURIComponent(id),{method:"POST"});o.innerHTML='<div class="panel" style="margin-top:12px"><h3>'+esc(r.verdict)+' — '+esc(r.risk_score)+'% RISK</h3><div class="panel-sub">'+(r.reasons||[]).map(esc).join(" • ")+'</div><div class="scan-row"><button onclick="report(\''+r.email_id+'\')">REPORT PDF</button><button onclick="quarantine(\''+r.email_id+'\')">QUARANTINE</button></div><div id="reportOutput"></div></div>';requestAnimationFrame(bind3DTilt);showToast("Analysis complete")}catch(e){o.textContent="Analysis failed: "+e.message}}
function pdfText(v){return String(v??"").replace(/[\\()]/g,m=>"\\"+m).replace(/[^\x20-\x7E]/g,"?")}
function wrapPdf(text,max=82){const words=String(text??"").split(/\s+/),lines=[];let line="";for(const w of words){if((line+" "+w).trim().length>max){if(line)lines.push(line);line=w}else line=(line+" "+w).trim()}if(line)lines.push(line);return lines}
function makeIncidentPdf(r){const i=r.indicators_of_compromise||{},rows=[];rows.push(["PHISHGUARD INCIDENT REPORT",18]);rows.push(["Evidence-Based Phishing Investigation",10]);rows.push(["",8]);rows.push(["Incident ID: "+r.email_id,11]);rows.push(["Verdict: "+r.verdict,12]);rows.push(["Risk Score: "+r.risk_score+"%",12]);rows.push(["",8]);rows.push(["EVIDENCE",13]);(r.evidence||[]).forEach(x=>wrapPdf("- "+x).forEach(y=>rows.push([y,10])));rows.push(["",8]);rows.push(["INDICATORS OF COMPROMISE",13]);wrapPdf("Sender: "+(i.sender||"None")).forEach(y=>rows.push([y,10]));(i.urls||[]).forEach(x=>wrapPdf("URL: "+x).forEach(y=>rows.push([y,10])));(i.attachments||[]).forEach(x=>wrapPdf("Attachment: "+(typeof x==="string"?x:JSON.stringify(x))).forEach(y=>rows.push([y,10])));if(!(i.urls||[]).length)rows.push(["URLs: None",10]);if(!(i.attachments||[]).length)rows.push(["Attachments: None",10]);rows.push(["",8]);rows.push(["RECOMMENDED ACTION",13]);wrapPdf(r.recommended_action||"No action specified.").forEach(y=>rows.push([y,10]));rows.push(["",8]);rows.push(["Generated by PhishGuard Security Operations Platform",9]);let y=790,stream="BT\n";for(const [text,size] of rows){if(y<55)break;stream+=`/F1 ${size} Tf 55 ${y} Td (${pdfText(text)}) Tj\n0 ${-(size+7)} Td\n`;y-=size+7}stream+="ET";const objects=[];objects[1]="<< /Type /Catalog /Pages 2 0 R >>";objects[2]="<< /Type /Pages /Kids [3 0 R] /Count 1 >>";objects[3]="<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>";objects[4]=`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`;objects[5]="<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>";let pdf="%PDF-1.4\n",offsets=[0];for(let n=1;n<=5;n++){offsets[n]=pdf.length;pdf+=`${n} 0 obj\n${objects[n]}\nendobj\n`}const xref=pdf.length;pdf+="xref\n0 6\n0000000000 65535 f \n";for(let n=1;n<=5;n++)pdf+=String(offsets[n]).padStart(10,"0")+" 00000 n \n";pdf+=`trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;return new Blob([pdf],{type:"application/pdf"})}
async function report(id){const o=document.getElementById("reportOutput");try{showToast("Generating incident PDF...");const r=await api("/report/"+encodeURIComponent(id)),blob=makeIncidentPdf(r),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="PhishGuard-Incident-Report-"+String(r.email_id).replace(/[^a-zA-Z0-9_-]/g,"_")+".pdf";document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);o.innerHTML='<div class="demo"><h4>Incident Report Ready</h4><p>'+esc(r.verdict)+' | Risk: '+esc(r.risk_score)+'%</p><p>PDF downloaded successfully.</p></div>';showToast("Incident report PDF downloaded")}catch(e){showToast("Report failed: "+e.message)}}
async function quarantine(id){try{const r=await api("/quarantine/"+encodeURIComponent(id),{method:"POST"});showToast("Email "+r.status)}catch(e){showToast("Quarantine failed: "+e.message)}}
async function loadCampaigns(){const o=document.getElementById("campaignOutput");o.innerHTML='<div class="scan-result">⏳ Loading campaign intelligence...</div>';try{const rows=await api("/campaigns");o.innerHTML=rows.length?rows.map(c=>'<div class="threat"><div><b>'+esc(c.campaign_id||"Detected Campaign")+'</b><small>'+esc(c.reason||c.description||"Related phishing emails detected")+'</small></div><span class="badge">CAMPAIGN</span></div>').join(""):'<div class="scan-result">No active campaign detected.</div>';requestAnimationFrame(bind3DTilt);document.getElementById("campaignPanel")?.scrollIntoView({behavior:"smooth"})}catch(e){o.textContent="Campaign load failed: "+e.message}}
function bind3DTilt(){if(matchMedia("(pointer:coarse)").matches)return;document.querySelectorAll(".dashboard-card,.panel,.login-card,.threat").forEach(el=>{if(el.dataset.tiltBound)return;el.dataset.tiltBound="1";el.addEventListener("mousemove",e=>{const r=el.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;const power=el.classList.contains("threat")?4:7;el.style.setProperty("--rx",(-y*power)+"deg");el.style.setProperty("--ry",(x*power)+"deg");el.style.setProperty("--mx",((x+.5)*100)+"%");el.style.setProperty("--my",((y+.5)*100)+"%");el.classList.add("tilting")});el.addEventListener("mouseleave",()=>{el.style.setProperty("--rx","0deg");el.style.setProperty("--ry","0deg");el.classList.remove("tilting")})})}
function initImmersiveUI(){const glow=document.createElement("div");glow.className="cursor-glow";document.body.appendChild(glow);const progress=document.createElement("div");progress.className="scroll-progress";document.body.appendChild(progress);if(!matchMedia("(pointer:coarse)").matches)document.addEventListener("mousemove",e=>{glow.style.transform=`translate3d(${e.clientX-110}px,${e.clientY-110}px,0)`;document.documentElement.style.setProperty("--px",e.clientX/window.innerWidth-.5);document.documentElement.style.setProperty("--py",e.clientY/window.innerHeight-.5)});addEventListener("scroll",()=>{const max=document.documentElement.scrollHeight-innerHeight;progress.style.transform=`scaleX(${max>0?scrollY/max:0})`;document.querySelectorAll(".panel,.dashboard-card").forEach(el=>{const r=el.getBoundingClientRect();if(r.top<innerHeight*.92)el.classList.add("revealed")})},{passive:true});document.querySelectorAll(".hero,.login-card").forEach(el=>el.classList.add("depth-layer"));bind3DTilt();setTimeout(bind3DTilt,1000)}
window.addEventListener("DOMContentLoaded",()=>{handleOAuthReturn();initImmersiveUI()});
